"""feat: add deletion requests, audit logs and consent column

Revision ID: ce041ac66df1
Revises: 3bed4c61dc53
Create Date: 2026-06-23 21:14:36.070519

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ce041ac66df1"
down_revision: Union[str, None] = "3bed4c61dc53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "consent_personal_data", sa.Boolean(), server_default="true", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "consent_personal_data")
    # ### end Alembic commands ###
