"""feat: implement application-level encryption for full_name

Revision ID: d1fe6c076fb7
Revises: ce041ac66df1
Create Date: 2026-06-24 22:27:26.880530

"""

from typing import Sequence, Union

import sqlalchemy as sa

import app.models
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1fe6c076fb7"
down_revision: Union[str, None] = "ce041ac66df1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "full_name",
        existing_type=sa.VARCHAR(length=100),
        type_=app.models.EncryptedString(length=255),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "full_name",
        existing_type=app.models.EncryptedString(length=255),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
